[versions]

android-sdk-min = '23'
android-sdk-target = '33'
android-sdk-compile = 'android-33'

kotlin = '1.7.20'

[libraries]

# Gradle plugin
gradle-plugin-android = 'com.android.tools.build:gradle:7.3.1'
gradle-plugin-kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
gradle-plugin-ktlint = 'org.jlleitschuh.gradle:ktlint-gradle:11.0.0'
gradle-plugin-gradleversions = 'com.github.ben-manes:gradle-versions-plugin:0.43.0'
gradle-plugin-detekt = 'io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.21.0'

# Language
kotlin = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk7', version.ref = 'kotlin' }
jdk-desugar = 'com.android.tools:desugar_jdk_libs:1.1.5' # Newer versions may have issues: https://issuetracker.google.com/issues/247730422

# Android + UI
material = 'com.google.android.material:material:1.7.0'
material-progressbar = 'me.zhanghai.android.materialprogressbar:library:1.6.1'
material-dialogs = 'com.afollestad.material-dialogs:core:3.3.0'
constraintlayout = 'androidx.constraintlayout:constraintlayout:2.1.4'
androidx-appcompat = 'androidx.appcompat:appcompat:1.5.1'
androidx-core = 'androidx.core:core:1.9.0'
androidx-fragment-ktx = 'androidx.fragment:fragment-ktx:1.5.4'
androidx-lifecycle-extensions = 'androidx.lifecycle:lifecycle-extensions:2.2.0'

# RxJava
rxjava = 'io.reactivex.rxjava3:rxjava:3.1.5'
rxjava-android = 'io.reactivex.rxjava3:rxandroid:3.0.0'

# Utilities
timber = 'com.jakewharton.timber:timber:5.0.1'
scrolls = "mobi.lab.scrolls:scrolls:2.0.9"
eventbus = 'org.greenrobot:eventbus:3.3.1'

# Testing
test-junit = 'junit:junit:4.13.2'
test-junit-kotlin = { module = 'org.jetbrains.kotlin:kotlin-test-junit', version.ref = 'kotlin' }
test-mockito-core = 'org.mockito:mockito-core:4.8.1'
test-mockito-kotlin = 'com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0'
test-androidx-archtesting = 'androidx.arch.core:core-testing:2.1.0'
test-androidx-testrunner = 'androidx.test:runner:1.4.0'
test-androidx-junit = 'androidx.test.ext:junit-ktx:1.1.3'
test-androidx-core = 'androidx.test:core-ktx:1.4.0'
test-androidx-espresso-core = 'androidx.test.espresso:espresso-core:3.4.0'
test-androidx-espresso-intents = 'androidx.test.espresso:espresso-intents:3.4.0'
